// Lightweight i18n. Language follows Telegram's UI (<html lang>): "ru*" → Russian,
// everything else → English (fallback). T(key) returns the localized string.
function curLang(){
    var l=(document.documentElement.lang||navigator.language||'en').toLowerCase();
    return l.indexOf('ru')===0 ? 'ru' : 'en';
}
var L={
    // burger menu / panel titles
    downloads:      {ru:'Загрузки',                 en:'Downloads'},
    addons:         {ru:'Дополнения',               en:'Add-ons'},
    addons_desc:    {ru:'Плагины, темы и скрипты',    en:'Plugins, themes and scripts'},
    proxy:          {ru:'Прокси',                   en:'Proxy'},
    proxy_desc:     {ru:'Встроенный Flowseal/CF',    en:'Built-in Flowseal/CF'},
    proxy_mode:     {ru:'Режим',                    en:'Mode'},
    proxy_auto:     {ru:'Автоматически',            en:'Automatic'},
    proxy_auto_desc:{ru:'Сначала напрямую, при сбое переключиться и запомнить', en:'Try direct first, switch on failure and remember'},
    proxy_always:   {ru:'Всегда через прокси',      en:'Always use proxy'},
    proxy_always_desc:{ru:'MTProto WebSocket через Flowseal/CF', en:'Route MTProto WebSockets through Flowseal/CF'},
    proxy_off:      {ru:'Выключено',                en:'Off'},
    proxy_off_desc: {ru:'Только прямое соединение', en:'Use direct connection only'},
    proxy_status:   {ru:'Состояние',                en:'Status'},
    proxy_active:   {ru:'Прокси активен',           en:'Proxy active'},
    proxy_direct:   {ru:'Прямое соединение',        en:'Direct connection'},
    proxy_auto_on:  {ru:'Автопереключение закреплено', en:'Automatic fallback is latched'},
    proxy_reset:    {ru:'Попробовать прямое подключение снова', en:'Try direct connection again'},
    proxy_reset_desc:{ru:'Забыть сохранённое переключение и снова проверить прямой доступ к Telegram и Web A', en:'Forget the saved switch and test direct access to Telegram and Web A again'},
    proxy_applied:  {ru:'Режим прокси изменён',     en:'Proxy mode changed'},
    proxy_saved:    {ru:'Настройки прокси сохранены', en:'Proxy settings saved'},
    proxy_enabled:  {ru:'Включено', en:'Enabled'},
    proxy_disabled: {ru:'Выключено', en:'Disabled'},
    proxy_route:    {ru:'Маршрут', en:'Route'},
    proxy_domains:  {ru:'Домены Cloudflare', en:'Cloudflare domains'},
    proxy_flowseal: {ru:'Автоматически из Flowseal', en:'Automatic from Flowseal'},
    proxy_custom:   {ru:'Свои домены', en:'Custom domains'},
    proxy_custom_hint:{ru:'Домены через запятую', en:'Comma-separated domains'},
    proxy_pin:      {ru:'Закрепить домен', en:'Pin domain'},
    proxy_rotate:   {ru:'Автоматическая ротация', en:'Automatic rotation'},
    proxy_refresh:  {ru:'Обновить список', en:'Refresh list'},
    proxy_refresh_desc:{ru:'Получить актуальные домены Flowseal', en:'Fetch the current Flowseal domains'},
    proxy_test:     {ru:'Проверить подключение', en:'Test connection'},
    proxy_test_desc:{ru:'Проверить доступность Telegram через текущий маршрут', en:'Check Telegram connectivity through the current route'},
    proxy_testing:  {ru:'Проверка соединения…', en:'Testing connectivity…'},
    proxy_test_ok:  {ru:'Подключение работает', en:'Connection is working'},
    proxy_test_bad: {ru:'Есть проблемы с подключением', en:'There are connection problems'},
    proxy_worker:   {ru:'Cloudflare Worker', en:'Cloudflare Worker'},
    proxy_worker_toggle:{ru:'Использовать свой Worker', en:'Use custom Worker'},
    proxy_worker_desc:{ru:'Свой Worker вместо CF Proxy', en:'Use your own Worker instead of CF Proxy'},
    proxy_worker_domains:{ru:'Домены Worker через запятую', en:'Worker domains, comma-separated'},
    proxy_dc_ips:   {ru:'DC → IP', en:'DC → IP'},
    proxy_dc_ips_desc:{ru:'Назначение для своего Worker, формат 2:149.154.167.51', en:'Destinations for custom Worker, e.g. 2:149.154.167.51'},
    proxy_auto_opts:{ru:'Автопереключение', en:'Automatic fallback'},
    proxy_failures: {ru:'Ошибок до переключения', en:'Failures before switching'},
    proxy_window:   {ru:'Окно ошибок, секунд', en:'Failure window, seconds'},
    proxy_web_fallback:{ru:'Fallback интерфейса Web A', en:'Web A interface fallback'},
    proxy_web_fallback_desc:{ru:'При блокировке web.telegram.org брать согласованную версию из TelegramOrg GitHub', en:'Use a version-pinned TelegramOrg GitHub build when web.telegram.org is blocked'},
    proxy_diag:     {ru:'Диагностика', en:'Diagnostics'},
    proxy_diag_current:{ru:'Текущее соединение', en:'Current connection'},
    proxy_copy:     {ru:'Копировать диагностику', en:'Copy diagnostics'},
    proxy_copy_desc:{ru:'Скопировать техническую информацию о соединении', en:'Copy technical connection information'},
    proxy_save:     {ru:'Сохранить', en:'Save'},
    dl_already:     {ru:'Уже скачивается',           en:'Already downloading'},
    app_settings:   {ru:'Настройки приложения',     en:'App settings'},
    changelog:      {ru:'Список изменений',          en:'Changelog'},
    check_updates:  {ru:'Проверить обновления',      en:'Check for updates'},
    // tray
    tray_show:      {ru:'Показать',                  en:'Show'},
    tray_settings:  {ru:'Настройки',                 en:'Settings'},
    tray_read_all:  {ru:'Прочитать всё',             en:'Mark all as read'},
    tray_quit:      {ru:'Выйти',                     en:'Quit'},
    // downloads panel
    dl_clear:       {ru:'Очистить',                  en:'Clear'},
    dl_clear_t:     {ru:'Очистить загрузки',         en:'Clear downloads'},
    dl_clear_m:     {ru:'Удалить все записи загрузок?<br><small style="color:#aaa">Файлы на диске также будут удалены.</small>', en:'Remove all download records?<br><small style="color:#aaa">Files on disk will be deleted too.</small>'},
    dl_empty:       {ru:'Нет загрузок',              en:'No downloads'},
    dl_done:        {ru:'Завершено',                 en:'Completed'},
    dl_waiting:     {ru:'Ожидание…',                 en:'Waiting…'},
    dl_show_folder: {ru:'Показать в папке',          en:'Show in folder'},
    dl_delete:      {ru:'Удалить',                   en:'Delete'},
    dl_not_found:   {ru:'Файл не найден',            en:'File not found'},
    dl_del_t:       {ru:'Удалить загрузку',          en:'Delete download'},
    // add-ons panel
    ad_folder:      {ru:'Папка',                     en:'Folder'},
    ad_builtin:     {ru:'Встроенные',                en:'Built-in'},
    ad_user:        {ru:'Пользовательские (.js / .crx)', en:'Custom (.js / .crx)'},
    ad_none:        {ru:'Нет пользовательских дополнений', en:'No custom add-ons'},
    ad_apply:       {ru:'Применить (перезагрузить)', en:'Apply (reload)'},
    addon_off:      {ru:'Выключено',                 en:'Off'},
    ad_del_t:       {ru:'Удалить дополнение',        en:'Delete add-on'},
    // changelog
    cl_current:     {ru:'текущая',                   en:'current'},
    cl_nodesc:      {ru:'Без описания',              en:'No description'},
    cl_empty:       {ru:'Список изменений пуст.',     en:'Changelog is empty.'},
    // app settings panel
    sec_downloads:  {ru:'Загрузки',                  en:'Downloads'},
    st_folder:      {ru:'Папка для файлов',          en:'Download folder'},
    choose:         {ru:'Выбрать',                   en:'Choose'},
    sec_window:     {ru:'Окно',                      en:'Window'},
    st_tray:        {ru:'Сворачивать в трей',        en:'Minimize to tray'},
    st_devtools:    {ru:'Консоль разработчика',      en:'Developer console'},
    sec_updates:    {ru:'Обновления',               en:'Updates'},
    st_auto_check:  {ru:'Проверять автоматически',   en:'Check automatically'},
    iv_30m:         {ru:'Каждые 30 мин',             en:'Every 30 min'},
    iv_1h:          {ru:'Каждый час',                en:'Every hour'},
    iv_12h:         {ru:'Каждые 12 ч',               en:'Every 12 h'},
    iv_24h:         {ru:'Раз в сутки',               en:'Once a day'},
    iv_3d:          {ru:'Раз в 3 дня',               en:'Every 3 days'},
    iv_7d:          {ru:'Раз в неделю',              en:'Once a week'},
    iv_30d:         {ru:'Раз в месяц',               en:'Once a month'},
    iv_never:       {ru:'Никогда',                   en:'Never'},
    st_check_now:   {ru:'Проверить сейчас',          en:'Check now'},
    st_checking:    {ru:'Проверка…',                 en:'Checking…'},
    st_uptodate:    {ru:'Установлена последняя версия', en:'You have the latest version'},
    st_check_err:   {ru:'Ошибка проверки',           en:'Check failed'},
    st_saved:       {ru:'Настройки сохранены',       en:'Settings saved'},
    st_save_err:    {ru:'Ошибка сохранения',         en:'Save error'},
    st_saved_short: {ru:'Сохранено',                 en:'Saved'},
    sec_data:       {ru:'Данные',                    en:'Data'},
    st_clear_cache: {ru:'Очистить кэш и перезагрузить', en:'Clear cache and reload'},
    st_clear_cache_sub:{ru:'Удаляет локальные данные и перезапускает страницу', en:'Deletes local data and restarts the page'},
    sec_about:      {ru:'О приложении',              en:'About'},
    st_version:     {ru:'Версия',                    en:'Version'},
    st_your_id:     {ru:'Ваш ID',                    en:'Your ID'},
    st_username:    {ru:'Username',                  en:'Username'},
    on_word:        {ru:'Вкл',                       en:'On'},
    off_word:       {ru:'Выкл',                      en:'Off'},
    about_app:      {ru:'О приложении',              en:'About'},
    // notification settings block
    ns_popup:       {ru:'Показывать всплывающие карточки', en:'Show popup cards'},
    ns_sound:       {ru:'Звук уведомлений',          en:'Notification sound'},
    ns_duration:    {ru:'Время на экране',           en:'Time on screen'},
    ns_sec_private: {ru:'Личные чаты',               en:'Private chats'},
    ns_sec_group:   {ru:'Группы',                    en:'Groups'},
    ns_sec_channel: {ru:'Каналы',                    en:'Channels'},
    ns_hide_text:   {ru:'Скрывать текст входящих сообщений', en:'Hide incoming message text'},
    ns_hide_sender: {ru:'Скрывать имя входящих сообщений',   en:'Hide incoming sender name'},
    ns_section:     {ru:'Всплывающие уведомления',   en:'Popup notifications'},
    unit_sec:       {ru:' с',                        en:' s'},
    // update notification / progress
    upd_title:      {ru:'Доступно обновление',       en:'Update available'},
    upd_avail:      {ru:'Доступна версия',           en:'Version available'},
    upd_now:        {ru:'сейчас',                    en:'current'},
    upd_download:   {ru:'СКАЧАТЬ',                   en:'DOWNLOAD'},
    upd_later:      {ru:'ПОЗЖЕ',                     en:'LATER'},
    upd_skip:       {ru:'ПРОПУСТИТЬ',                en:'SKIP'},
    upd_checking:   {ru:'Проверка обновлений…',      en:'Checking for updates…'},
    upd_dl:         {ru:'Скачивание',                en:'Downloading'},
    upd_preparing:  {ru:'Подготовка…',               en:'Preparing…'},
    upd_downloaded: {ru:'Скачано',                   en:'Downloaded'},
    upd_installing: {ru:'Запуск установщика…',       en:'Launching installer…'},
    // download statuses
    dl_clear_upper: {ru:'ОЧИСТИТЬ',                  en:'CLEAR'},
    dl_st_pending:  {ru:'Ожидание…',                 en:'Waiting…'},
    dl_st_downloading:{ru:'⬇ Загружается',           en:'⬇ Downloading'},
    dl_st_completed:{ru:'✓ Завершено',               en:'✓ Completed'},
    dl_st_failed:   {ru:'✕ Ошибка',                  en:'✕ Failed'},
    dl_st_cancelled:{ru:'— Отменено',                en:'— Cancelled'},
    // download corner indicator
    dl_card_downloading:{ru:'Скачивание…',           en:'Downloading…'},
    dl_card_saved:  {ru:'Сохранено',                 en:'Saved'},
    dl_card_failed: {ru:'Не удалось скачать',         en:'Download failed'},
    dl_card_open:   {ru:'Нажмите, чтобы открыть',     en:'Click to open'},
    dl_card_file:   {ru:'Файл',                       en:'File'},
    // what's new (one-time on version bump)
    wn_title:       {ru:'Что нового',                en:"What's new"},
    wn_intro:       {ru:'В этой версии:',            en:'In this version:'},
    wn_1:           {ru:'Переработан весь дизайн - большинство настроек перенесены в оригинальные меню и подменю Telegram.', en:'The whole design was reworked - most settings now live inside the native Telegram menus and submenus.'},
    wn_2:           {ru:'В «Настройки → Уведомления» теперь можно включить всплывающие карточки уведомлений.', en:'In Settings → Notifications you can now enable popup notification cards.'},
    wn_3:           {ru:'Загрузки теперь работают прямо в сообщениях.', en:'Downloads now work right inside messages.'},
    wn_ok:          {ru:'ПОНЯТНО',                   en:'GOT IT'},
    // media-type previews for notifications (when message has no text)
    mt_photo:       {ru:'Фото',                      en:'Photo'},
    mt_video:       {ru:'Видео',                     en:'Video'},
    mt_gif:         {ru:'GIF',                        en:'GIF'},
    mt_round:       {ru:'Видеосообщение',            en:'Video message'},
    mt_voice:       {ru:'Голосовое сообщение',       en:'Voice message'},
    mt_audio:       {ru:'Аудио',                     en:'Audio'},
    mt_file:        {ru:'Файл',                       en:'File'},
    mt_sticker:     {ru:'Стикер',                     en:'Sticker'},
    mt_poll:        {ru:'Опрос',                      en:'Poll'},
    mt_contact:     {ru:'Контакт',                    en:'Contact'},
    mt_location:    {ru:'Геопозиция',                 en:'Location'},
    // misc UI
    new_message:    {ru:'Новое сообщение',           en:'New message'},
    ctx_open_folder:{ru:'Открыть папку',             en:'Open folder'},
    dl_not_found_long:{ru:'Файл не найден — возможно, перемещён или удалён', en:'File not found — it may have been moved or deleted'},
    // common
    back:           {ru:'Назад',                     en:'Back'},
    loading:        {ru:'Загрузка…',                 en:'Loading…'},
    load_error:     {ru:'Ошибка загрузки',           en:'Load error'},
    error:          {ru:'Ошибка',                    en:'Error'},
    ok:             {ru:'ОК',                        en:'OK'},
    cancel:         {ru:'ОТМЕНА',                    en:'CANCEL'},
    del_upper:      {ru:'УДАЛИТЬ',                   en:'DELETE'},
    save_upper:     {ru:'СОХРАНИТЬ',                 en:'SAVE'},
};
function T(k){ var e=L[k]; if(!e) return k; return e[curLang()]||e.en||k; }
