// Lightweight i18n. Language follows Telegram's UI (<html lang>): "ru*" → Russian,
// everything else → English (fallback). T(key) returns the localized string.
function curLang(){
    var l=(document.documentElement.lang||navigator.language||'en').toLowerCase();
    return l.indexOf('ru')===0 ? 'ru' : 'en';
}
var L={
    // burger menu / panel titles
    downloads:      {ru:'Загрузки',                 en:'Downloads'},
    downloads_desc: {ru:'История загрузок и папка сохранения', en:'Download history and save folder'},
    addons:         {ru:'Дополнения',               en:'Add-ons'},
    twd_settings_desc:{ru:'Настройки Telegram Web Desktop', en:'Telegram Web Desktop settings'},
    twd_mod_info:   {ru:'Модификация Telegram Web A', en:'Telegram Web A modification'},
    twd_general:    {ru:'Общее', en:'General'},
    twd_general_desc:{ru:'Окно и интеграция с Windows', en:'Window and Windows integration'},
    twd_appearance: {ru:'Внешний вид', en:'Appearance'},
    twd_appearance_desc:{ru:'Расположение сообщений и элементы интерфейса', en:'Message layout and interface elements'},
    twd_messages:   {ru:'Сообщения', en:'Messages'},
    twd_messages_desc:{ru:'Приватность, удалённые сообщения и история редактирования', en:'Privacy, deleted messages, and edit history'},
    twd_notifications:{ru:'Уведомления', en:'Notifications'},
    twd_notifications_desc:{ru:'Всплывающие карточки, звук и приватность', en:'Popup cards, sound and privacy'},
    twd_updates_desc:{ru:'Проверка обновлений и список изменений', en:'Update checks and changelog'},
    twd_data_desc:  {ru:'Кэш и локальная история', en:'Cache and local history'},
    twd_about_desc: {ru:'Версия и служебная информация', en:'Version and service information'},
    twd_reload_notice:{ru:'Страница будет перезагружена', en:'The page will be reloaded'},
    twd_layout:     {ru:'Расположение сообщений', en:'Message layout'},
    twd_layout_desc:{ru:'Как сообщения располагаются в области чата', en:'How messages are positioned in the chat area'},
    twd_layout_native:{ru:'Стандартное Telegram', en:'Telegram default'},
    twd_layout_left:{ru:'Сообщения слева', en:'Messages on the left'},
    twd_layout_wide:{ru:'Широкие сообщения слева', en:'Wide messages on the left'},
    twd_hide_ads:   {ru:'Скрывать рекламу Telegram', en:'Hide Telegram ads'},
    twd_hide_ads_desc:{ru:'Скрывать рекламные блоки в нижней части чатов и каналов', en:'Hide sponsored blocks at the bottom of chats and channels'},
    twd_no_read:{ru:'Нечиталка везде', en:'Never send read receipts'},
    twd_no_read_desc:{ru:'Не помечает входящие сообщения как прочитанные', en:'Do not mark incoming messages as read'},
    twd_no_typing:{ru:'Неписалка везде', en:'Hide typing everywhere'},
    twd_no_typing_desc:{ru:'Не показывает собеседникам, что вы печатаете или записываете голосовое сообщение', en:'Do not show others when you are typing or recording a voice message'},
    twd_privacy_personal:{ru:'Персональные настройки', en:'Personal settings'},
    twd_privacy_personal_desc:{ru:'Нечиталка и неписалка для отдельных чатов', en:'Read and typing privacy for individual chats'},
    twd_privacy_personal_empty:{ru:'Персональных настроек пока нет', en:'No personal settings yet'},
    twd_privacy_read_on:{ru:'Нечиталка включена', en:'Read privacy enabled'},
    twd_privacy_read_off:{ru:'Нечиталка выключена', en:'Read privacy disabled'},
    twd_privacy_typing_on:{ru:'Неписалка включена', en:'Typing privacy enabled'},
    twd_privacy_typing_off:{ru:'Неписалка выключена', en:'Typing privacy disabled'},
    ctx_no_typing_on:{ru:'Включить неписалку', en:'Enable typing privacy'},
    ctx_no_typing_off:{ru:'Выключить неписалку', en:'Disable typing privacy'},
    ctx_no_read_on:{ru:'Включить нечиталку', en:'Enable read privacy'},
    ctx_no_read_off:{ru:'Выключить нечиталку', en:'Disable read privacy'},
    twd_show_deleted:{ru:'Показывать удалённые сообщения', en:'Show deleted messages'},
    twd_show_deleted_desc:{ru:'Отображаются до обновления страницы', en:'Shown until the page is reloaded'},
    twd_show_disappearing:{ru:'Показывать исчезающие сообщения', en:'Show disappearing messages'},
    twd_show_disappearing_desc:{ru:'Отображаются до обновления страницы', en:'Shown until the page is reloaded'},
    twd_save_deleted:{ru:'Сохранять удалённые сообщения', en:'Save deleted messages'},
    twd_save_deleted_desc:{ru:'Сохраняет сообщения в локальное хранилище для последующего просмотра в любое время через меню действий с чатом', en:'Saves messages to local storage for later viewing at any time from the chat actions menu'},
    twd_save_disappearing:{ru:'Сохранять все исчезающие сообщения', en:'Save all disappearing messages'},
    twd_save_disappearing_desc:{ru:'Сохраняет сообщения в локальное хранилище для последующего просмотра в любое время через меню действий с чатом', en:'Saves messages to local storage for later viewing at any time from the chat actions menu'},
    twd_edit_history:{ru:'Сохранять историю редактирования всех сообщений', en:'Save edit history for all messages'},
    twd_edit_history_desc:{ru:'Для просмотра необходимо нажать на «(ред.)» на любом измененном сообщении или выбрать соответствующий пункт из меню действий с сообщением.', en:'To view it, click “(edited)” on any edited message or choose the corresponding item from the message actions menu.'},
    twd_save_public:{ru:'Сохранять публичные чаты', en:'Save public chats'},
    twd_save_public_desc:{ru:'Включает историю сообщений для групп и каналов', en:'Enables message history for groups and channels'},
    twd_history_scope:{ru:'Метод сохранения сообщений', en:'Message storage method'},
    twd_history_scope_chat:{ru:'Пока открыт чат', en:'While the chat is open'},
    twd_history_scope_client:{ru:'Активный процесс', en:'Active process'},
    twd_history_scope_always:{ru:'Всегда', en:'Always'},
    twd_history_limits:{ru:'Ограничение истории: до 5000 сообщений и до 20 предыдущих версий каждого сообщения.', en:'History limit: up to 5,000 messages and up to 20 previous versions per message.'},
    twd_message_storage:{ru:'Сохранение', en:'Storage'},
    twd_clear_history:{ru:'Очистить историю сообщений', en:'Clear message history'},
    twd_clear_history_desc:{ru:'Удалить сохранённые удаления, исчезающие сообщения и версии редактирования', en:'Delete saved deletions, disappearing messages, and edit versions'},
    twd_clear_history_confirm:{ru:'Очистить всю сохранённую историю сообщений?', en:'Clear all saved message history?'},
    twd_history_cleared:{ru:'История сообщений очищена', en:'Message history cleared'},
    twd_local_data:{ru:'Локальные данные', en:'Local data'},
    twd_notif_volume:{ru:'Громкость уведомлений', en:'Notification volume'},
    twd_notif_check:{ru:'Проверить', en:'Check'},
    twd_notif_check_desc:{ru:'Показать тестовое уведомление с текущими настройками звука, времени и приватности', en:'Show a test notification with the current sound, duration, and privacy settings'},
    twd_notif_check_sender:{ru:'Андрей Ветров', en:'Andrew Wells'},
    twd_notif_check_body:{ru:'Так будет выглядеть входящее сообщение.', en:'This is how an incoming message will look.'},
    twd_notif_check_error:{ru:'Не удалось показать тестовое уведомление', en:'Could not show the test notification'},
    twd_categories: {ru:'Категории', en:'Categories'},
    twd_privacy:    {ru:'Конфиденциальность', en:'Privacy'},
    twd_changelog_desc:{ru:'Что изменилось в версиях приложения', en:'Changes across application versions'},
    twd_ui_lab_desc:{ru:'Служебная диагностика интерфейса', en:'Internal interface diagnostics'},
    twd_download_default_folder:{ru:'Системная папка «Загрузки»', en:'System Downloads folder'},
    twd_download_history:{ru:'История загрузок', en:'Download history'},
    addons_desc:    {ru:'Плагины, темы и скрипты',    en:'Plugins, themes and scripts'},
    proxy:          {ru:'Прокси',                   en:'Proxy'},
    proxy_desc:     {ru:'Встроенный Flowseal/CF',    en:'Built-in Flowseal/CF'},
    proxy_mode:     {ru:'Режим',                    en:'Mode'},
    proxy_auto:     {ru:'Автоматически',            en:'Automatic'},
    proxy_auto_desc:{ru:'Сначала напрямую, при сбое переключиться и запомнить', en:'Try direct first, switch on failure and remember'},
    proxy_always:   {ru:'Всегда через прокси',      en:'Always use proxy'},
    proxy_always_desc:{ru:'MTProto WebSocket через Flowseal/CF', en:'Route MTProto WebSockets through Flowseal/CF'},
    proxy_off:      {ru:'Выключено',                en:'Off'},
    proxy_off_desc: {ru:'Только прямое соединение', en:'Use direct connection only'},
    proxy_status:   {ru:'Состояние',                en:'Status'},
    proxy_active:   {ru:'Прокси активен',           en:'Proxy active'},
    proxy_direct:   {ru:'Прямое соединение',        en:'Direct connection'},
    proxy_auto_on:  {ru:'Автопереключение закреплено', en:'Automatic fallback is latched'},
    proxy_reset:    {ru:'Попробовать прямое подключение снова', en:'Try direct connection again'},
    proxy_reset_desc:{ru:'Забыть сохранённое переключение и снова проверить прямой доступ к Telegram и Web A', en:'Forget the saved switch and test direct access to Telegram and Web A again'},
    proxy_applied:  {ru:'Режим прокси изменён',     en:'Proxy mode changed'},
    proxy_saved:    {ru:'Настройки прокси сохранены', en:'Proxy settings saved'},
    proxy_enabled:  {ru:'Включено', en:'Enabled'},
    proxy_disabled: {ru:'Выключено', en:'Disabled'},
    proxy_route:    {ru:'Маршрут', en:'Route'},
    proxy_domains:  {ru:'Домены Cloudflare', en:'Cloudflare domains'},
    proxy_flowseal: {ru:'Автоматически из Flowseal', en:'Automatic from Flowseal'},
    proxy_custom:   {ru:'Свои домены', en:'Custom domains'},
    proxy_custom_hint:{ru:'Домены через запятую', en:'Comma-separated domains'},
    proxy_pin:      {ru:'Закрепить домен', en:'Pin domain'},
    proxy_rotate:   {ru:'Автоматическая ротация', en:'Automatic rotation'},
    proxy_refresh:  {ru:'Обновить список', en:'Refresh list'},
    proxy_refresh_desc:{ru:'Получить актуальные домены Flowseal', en:'Fetch the current Flowseal domains'},
    proxy_test:     {ru:'Проверить подключение', en:'Test connection'},
    proxy_test_desc:{ru:'Проверить доступность Telegram через текущий маршрут', en:'Check Telegram connectivity through the current route'},
    proxy_testing:  {ru:'Проверка соединения…', en:'Testing connectivity…'},
    proxy_test_ok:  {ru:'Подключение работает', en:'Connection is working'},
    proxy_test_bad: {ru:'Есть проблемы с подключением', en:'There are connection problems'},
    proxy_worker:   {ru:'Cloudflare Worker', en:'Cloudflare Worker'},
    proxy_worker_toggle:{ru:'Использовать свой Worker', en:'Use custom Worker'},
    proxy_worker_desc:{ru:'Свой Worker вместо CF Proxy', en:'Use your own Worker instead of CF Proxy'},
    proxy_worker_domains:{ru:'Домены Worker через запятую', en:'Worker domains, comma-separated'},
    proxy_dc_ips:   {ru:'DC → IP', en:'DC → IP'},
    proxy_dc_ips_desc:{ru:'Назначение для своего Worker, формат 2:149.154.167.51', en:'Destinations for custom Worker, e.g. 2:149.154.167.51'},
    proxy_auto_opts:{ru:'Автопереключение', en:'Automatic fallback'},
    proxy_failures: {ru:'Ошибок до переключения', en:'Failures before switching'},
    proxy_window:   {ru:'Окно ошибок, секунд', en:'Failure window, seconds'},
    proxy_web_fallback:{ru:'Fallback интерфейса Web A', en:'Web A interface fallback'},
    proxy_web_fallback_desc:{ru:'При блокировке web.telegram.org брать согласованную версию из TelegramOrg GitHub', en:'Use a version-pinned TelegramOrg GitHub build when web.telegram.org is blocked'},
    proxy_diag:     {ru:'Диагностика', en:'Diagnostics'},
    proxy_diag_current:{ru:'Текущее соединение', en:'Current connection'},
    proxy_copy:     {ru:'Копировать диагностику', en:'Copy diagnostics'},
    proxy_copy_desc:{ru:'Скопировать техническую информацию о соединении', en:'Copy technical connection information'},
    proxy_save:     {ru:'Сохранить', en:'Save'},
    dl_already:     {ru:'Уже скачивается',           en:'Already downloading'},
    app_settings:   {ru:'Настройки приложения',     en:'App settings'},
    changelog:      {ru:'Список изменений',          en:'Changelog'},
    check_updates:  {ru:'Проверить обновления',      en:'Check for updates'},
    // tray
    tray_show:      {ru:'Показать',                  en:'Show'},
    tray_settings:  {ru:'Настройки',                 en:'Settings'},
    tray_read_all:  {ru:'Прочитать всё',             en:'Mark all as read'},
    tray_quit:      {ru:'Выйти',                     en:'Quit'},
    // downloads panel
    dl_clear:       {ru:'Очистить',                  en:'Clear'},
    dl_clear_t:     {ru:'Очистить загрузки',         en:'Clear downloads'},
    dl_clear_m:     {ru:'Удалить все записи загрузок?<br><small style="color:#aaa">Файлы на диске также будут удалены.</small>', en:'Remove all download records?<br><small style="color:#aaa">Files on disk will be deleted too.</small>'},
    dl_empty:       {ru:'Нет загрузок',              en:'No downloads'},
    dl_done:        {ru:'Завершено',                 en:'Completed'},
    dl_waiting:     {ru:'Ожидание…',                 en:'Waiting…'},
    dl_show_folder: {ru:'Показать в папке',          en:'Show in folder'},
    dl_folder:      {ru:'Папка',                     en:'Folder'},
    dl_open:        {ru:'Открыть',                   en:'Open'},
    dl_downloading: {ru:'Загружается',               en:'Downloading'},
    dl_failed:      {ru:'Ошибка',                    en:'Failed'},
    dl_cancelled:   {ru:'Отменено',                  en:'Cancelled'},
    dl_delete:      {ru:'Удалить',                   en:'Delete'},
    dl_not_found:   {ru:'Файл не найден',            en:'File not found'},
    dl_del_t:       {ru:'Удалить загрузку',          en:'Delete download'},
    dl_delete_disk: {ru:'Файл также будет удалён с диска.', en:'The file will also be deleted from disk.'},
    // add-ons panel
    ad_folder:      {ru:'Папка',                     en:'Folder'},
    ad_builtin:     {ru:'Встроенные',                en:'Built-in'},
    ad_user:        {ru:'Пользовательские (.js / .crx)', en:'Custom (.js / .crx)'},
    ad_none:        {ru:'Нет пользовательских дополнений', en:'No custom add-ons'},
    ad_reload_toggle:{ru:'Сохранить изменение?', en:'Save this change?'},
    addon_off:      {ru:'Выключено',                 en:'Off'},
    ad_del_t:       {ru:'Удалить дополнение',        en:'Delete add-on'},
    // changelog
    cl_current:     {ru:'текущая',                   en:'current'},
    cl_nodesc:      {ru:'Без описания',              en:'No description'},
    cl_empty:       {ru:'Список изменений пуст.',     en:'Changelog is empty.'},
    // app settings panel
    sec_downloads:  {ru:'Загрузки',                  en:'Downloads'},
    st_folder:      {ru:'Папка для файлов',          en:'Download folder'},
    choose:         {ru:'Выбрать',                   en:'Choose'},
    sec_window:     {ru:'Окно',                      en:'Window'},
    st_tray:        {ru:'Сворачивать в трей',        en:'Minimize to tray'},
    st_tray_sub:    {ru:'Оставлять приложение запущенным и получать уведомления после закрытия окна', en:'Keep the app running and receive notifications after closing the window'},
    st_devtools:    {ru:'Консоль разработчика',      en:'Developer console'},
    sec_integration:{ru:'Интеграция',                en:'Integration'},
    st_tg_links:    {ru:'Ссылки tg://',              en:'tg:// links'},
    st_tg_links_sub:{ru:'Выбрать приложение для ссылок Telegram в параметрах Windows', en:'Choose the app for Telegram links in Windows Settings'},
    st_open_defaults:{ru:'Настроить',                 en:'Configure'},
    sec_updates:    {ru:'Обновления',               en:'Updates'},
    st_auto_check:  {ru:'Проверять автоматически',   en:'Check automatically'},
    iv_30m:         {ru:'Каждые 30 мин',             en:'Every 30 min'},
    iv_1h:          {ru:'Каждый час',                en:'Every hour'},
    iv_12h:         {ru:'Каждые 12 ч',               en:'Every 12 h'},
    iv_24h:         {ru:'Раз в сутки',               en:'Once a day'},
    iv_3d:          {ru:'Раз в 3 дня',               en:'Every 3 days'},
    iv_7d:          {ru:'Раз в неделю',              en:'Once a week'},
    iv_30d:         {ru:'Раз в месяц',               en:'Once a month'},
    iv_never:       {ru:'Никогда',                   en:'Never'},
    st_check_now:   {ru:'Проверить сейчас',          en:'Check now'},
    st_checking:    {ru:'Проверка…',                 en:'Checking…'},
    st_uptodate:    {ru:'Установлена последняя версия', en:'You have the latest version'},
    st_check_err:   {ru:'Ошибка проверки',           en:'Check failed'},
    st_saved:       {ru:'Настройки сохранены',       en:'Settings saved'},
    st_save_err:    {ru:'Ошибка сохранения',         en:'Save error'},
    st_saved_short: {ru:'Сохранено',                 en:'Saved'},
    sec_data:       {ru:'Данные',                    en:'Data'},
    st_clear_cache: {ru:'Очистить кэш и перезагрузить', en:'Clear cache and reload'},
    st_clear_cache_sub:{ru:'Удаляет локальные данные и перезапускает страницу', en:'Deletes local data and restarts the page'},
    sec_about:      {ru:'О приложении',              en:'About'},
    st_version:     {ru:'Версия',                    en:'Version'},
    st_your_id:     {ru:'Ваш ID',                    en:'Your ID'},
    st_username:    {ru:'Username',                  en:'Username'},
    on_word:        {ru:'Вкл',                       en:'On'},
    off_word:       {ru:'Выкл',                      en:'Off'},
    about_app:      {ru:'О приложении',              en:'About'},
    // hidden UI laboratory
    ui_lab:         {ru:'UI Lab',                     en:'UI Lab'},
    ui_lab_unlock_left:{ru:'Осталось ещё: ',          en:'Remaining: '},
    ui_lab_rows:    {ru:'Строки',                     en:'Rows'},
    ui_lab_controls:{ru:'Элементы управления',        en:'Controls'},
    ui_lab_buttons: {ru:'Кнопки и hover/ripple',      en:'Buttons and hover/ripple'},
    ui_lab_notifications:{ru:'Диагностика уведомлений', en:'Notification diagnostics'},
    ui_lab_feedback:{ru:'Модалки и уведомления',      en:'Modals and notifications'},
    ui_lab_popup_states:{ru:'Состояния desktop popup', en:'Desktop popup states'},
    ui_lab_popup_avatar_text:{ru:'Аватар + текст',    en:'Avatar + text'},
    ui_lab_popup_avatar_text_sub:{ru:'Обычный popup с аватаркой и видимым текстом', en:'Normal popup with avatar and visible text'},
    ui_lab_popup_avatar_hidden:{ru:'Аватар + скрытый текст', en:'Avatar + hidden text'},
    ui_lab_popup_avatar_hidden_sub:{ru:'Имя и аватар видны, содержимое сообщения скрыто', en:'Sender and avatar visible, message text hidden'},
    ui_lab_popup_hidden_sender:{ru:'Скрытый отправитель', en:'Hidden sender'},
    ui_lab_popup_hidden_sender_sub:{ru:'Без аватарки и имени, текст сообщения виден', en:'No avatar or sender name, message text visible'},
    ui_lab_popup_hidden_all:{ru:'Всё скрыто',          en:'Everything hidden'},
    ui_lab_popup_hidden_all_sub:{ru:'Скрыты отправитель, аватар и текст сообщения', en:'Sender, avatar and message text hidden'},
    ui_lab_popup_no_avatar:{ru:'Без аватарки',        en:'No avatar'},
    ui_lab_popup_no_avatar_sub:{ru:'Проверка буквенного fallback-аватара', en:'Tests the letter fallback avatar'},
    ui_lab_popup_long:{ru:'Длинный текст',            en:'Long text'},
    ui_lab_popup_long_sub:{ru:'Проверка переноса строк и высоты карточки', en:'Tests wrapping and card height'},
    ui_lab_popup_stack:{ru:'Стек из трёх popup',      en:'Three-popup stack'},
    ui_lab_popup_stack_sub:{ru:'Одновременно показывает три разных состояния', en:'Shows three different states at once'},
    ui_lab_popup_text:{ru:'Тестовое сообщение с видимым текстом.', en:'Test message with visible text.'},
    ui_lab_popup_long_text:{ru:'Это длинное тестовое сообщение для проверки переноса строк, высоты карточки, отступов и поведения кнопок в расширенном desktop popup.', en:'This is a long test message for checking wrapping, card height, spacing, and button behavior in the expanded desktop popup.'},
    ui_lab_downloads:{ru:'Состояния загрузок',        en:'Download states'},
    ui_lab_proxy:   {ru:'Прокси и статусы',           en:'Proxy and status'},
    ui_lab_plain:   {ru:'Обычная строка',             en:'Plain row'},
    ui_lab_plain_sub:{ru:'Собрано из живых компонентов Telegram', en:'Built from live Telegram components'},
    ui_lab_action:  {ru:'Интерактивная строка',       en:'Interactive row'},
    ui_lab_action_sub:{ru:'Проверка hover и ripple',  en:'Hover and ripple check'},
    ui_lab_decorated:{ru:'Строка с нативной иконкой', en:'Native icon row'},
    ui_lab_checkbox:{ru:'Checkbox',                   en:'Checkbox'},
    ui_lab_switch:  {ru:'Switcher',                   en:'Switcher'},
    ui_lab_input:   {ru:'Поле ввода',                 en:'Input'},
    ui_lab_textarea:{ru:'Многострочное поле',         en:'Textarea'},
    ui_lab_picker:  {ru:'Picker',                     en:'Picker'},
    ui_lab_picker_sub:{ru:'Нативная radio-модалка',   en:'Native radio modal'},
    ui_lab_primary: {ru:'ОСНОВНАЯ',                   en:'PRIMARY'},
    ui_lab_danger:  {ru:'ОПАСНАЯ',                    en:'DANGER'},
    ui_lab_hover:   {ru:'Hover/ripple работает',      en:'Hover/ripple works'},
    ui_lab_ok:      {ru:'Исправно',                   en:'Healthy'},
    ui_lab_bad:     {ru:'Неисправно',                 en:'Broken'},
    ui_lab_running: {ru:'Работает',                   en:'Running'},
    ui_lab_stopped: {ru:'Остановлен',                 en:'Stopped'},
    ui_lab_notif_interceptor:{ru:'Перехватчик',       en:'Interceptor'},
    ui_lab_notif_sw:{ru:'ServiceWorker hook',         en:'ServiceWorker hook'},
    ui_lab_notif_shim:{ru:'Notification shim',        en:'Notification shim'},
    ui_lab_notif_health:{ru:'Health timer',            en:'Health timer'},
    ui_lab_notif_repair:{ru:'Repair routine',         en:'Repair routine'},
    ui_lab_notif_repair_now:{ru:'Восстановить сейчас', en:'Repair now'},
    ui_lab_notif_repair_sub:{ru:'Переустановить хуки без перезагрузки страницы', en:'Reinstall hooks without reloading the page'},
    ui_lab_notif_capture:{ru:'Проверить перехват',    en:'Test interception'},
    ui_lab_notif_capture_sub:{ru:'Локальный ServiceWorker probe без реального уведомления', en:'Local ServiceWorker probe without a real notification'},
    ui_lab_capture_ok:{ru:'Перехват работает',        en:'Interception works'},
    ui_lab_capture_bad:{ru:'Перехват не сработал',    en:'Interception failed'},
    ui_lab_feedback_sub:{ru:'Безопасная демонстрация без изменения данных', en:'Safe demo without changing data'},
    ui_lab_toast:   {ru:'Toast',                      en:'Toast'},
    ui_lab_corner:  {ru:'Карточка в окне',            en:'In-window notification'},
    ui_lab_popup:   {ru:'Desktop popup',              en:'Desktop popup'},
    ui_lab_modal:   {ru:'Modal',                      en:'Modal'},
    ui_lab_loading: {ru:'Состояние загрузки',         en:'Loading state'},
    ui_lab_loading_sub:{ru:'Локальная имитация, без сети', en:'Local simulation, no network'},
    ui_lab_ready:   {ru:'Готово',                     en:'Ready'},
    ui_lab_destructive:{ru:'Destructive action',      en:'Destructive action'},
    ui_lab_destructive_sub:{ru:'Только демонстрация подтверждения, ничего не удаляет', en:'Confirmation demo only; deletes nothing'},
    ui_lab_demo:    {ru:'Демонстрация UI Lab',        en:'UI Lab demo'},
    // notification settings block
    ns_popup:       {ru:'Показывать всплывающие карточки', en:'Show popup cards'},
    ns_sound:       {ru:'Звук уведомлений',          en:'Notification sound'},
    ns_duration:    {ru:'Время на экране',           en:'Time on screen'},
    ns_sec_private: {ru:'Личные чаты',               en:'Private chats'},
    ns_sec_group:   {ru:'Группы',                    en:'Groups'},
    ns_sec_channel: {ru:'Каналы',                    en:'Channels'},
    ns_hide_text:   {ru:'Скрывать текст входящих сообщений', en:'Hide incoming message text'},
    ns_hide_sender: {ru:'Скрывать имя входящих сообщений',   en:'Hide incoming sender name'},
    ns_hide_avatar: {ru:'Скрывать аватарки входящих сообщений', en:'Hide incoming message avatars'},
    ns_section:     {ru:'Всплывающие уведомления',   en:'Popup notifications'},
    unit_sec:       {ru:' с',                        en:' s'},
    // update notification / progress
    upd_title:      {ru:'Доступно обновление',       en:'Update available'},
    upd_avail:      {ru:'Доступна версия',           en:'Version available'},
    upd_now:        {ru:'сейчас',                    en:'current'},
    upd_download:   {ru:'СКАЧАТЬ',                   en:'DOWNLOAD'},
    upd_later:      {ru:'ПОЗЖЕ',                     en:'LATER'},
    upd_skip:       {ru:'ПРОПУСТИТЬ',                en:'SKIP'},
    upd_checking:   {ru:'Проверка обновлений…',      en:'Checking for updates…'},
    upd_dl:         {ru:'Скачивание',                en:'Downloading'},
    upd_preparing:  {ru:'Подготовка…',               en:'Preparing…'},
    upd_downloaded: {ru:'Скачано',                   en:'Downloaded'},
    upd_installing: {ru:'Запуск установщика…',       en:'Launching installer…'},
    // download statuses
    dl_clear_upper: {ru:'ОЧИСТИТЬ',                  en:'CLEAR'},
    dl_st_pending:  {ru:'Ожидание…',                 en:'Waiting…'},
    dl_st_downloading:{ru:'⬇ Загружается',           en:'⬇ Downloading'},
    dl_st_completed:{ru:'✓ Завершено',               en:'✓ Completed'},
    dl_st_failed:   {ru:'✕ Ошибка',                  en:'✕ Failed'},
    dl_st_cancelled:{ru:'— Отменено',                en:'— Cancelled'},
    // download corner indicator
    dl_card_downloading:{ru:'Скачивание…',           en:'Downloading…'},
    dl_card_saved:  {ru:'Сохранено',                 en:'Saved'},
    dl_card_failed: {ru:'Не удалось скачать',         en:'Download failed'},
    dl_card_open:   {ru:'Нажмите, чтобы открыть',     en:'Click to open'},
    dl_card_file:   {ru:'Файл',                       en:'File'},
    // what's new (one-time on version bump)
    wn_title:       {ru:'Что нового',                en:"What's new"},
    wn_intro:       {ru:'В этой версии:',            en:'In this version:'},
    wn_1:           {ru:'Переработан весь дизайн - большинство настроек перенесены в оригинальные меню и подменю Telegram.', en:'The whole design was reworked - most settings now live inside the native Telegram menus and submenus.'},
    wn_2:           {ru:'В «Настройки → Уведомления» теперь можно включить всплывающие карточки уведомлений.', en:'In Settings → Notifications you can now enable popup notification cards.'},
    wn_3:           {ru:'Загрузки теперь работают прямо в сообщениях.', en:'Downloads now work right inside messages.'},
    wn_ok:          {ru:'ПОНЯТНО',                   en:'GOT IT'},
    // media-type previews for notifications (when message has no text)
    mt_photo:       {ru:'Фото',                      en:'Photo'},
    mt_video:       {ru:'Видео',                     en:'Video'},
    mt_gif:         {ru:'GIF',                        en:'GIF'},
    mt_round:       {ru:'Видеосообщение',            en:'Video message'},
    mt_voice:       {ru:'Голосовое сообщение',       en:'Voice message'},
    mt_audio:       {ru:'Аудио',                     en:'Audio'},
    mt_file:        {ru:'Файл',                       en:'File'},
    mt_sticker:     {ru:'Стикер',                     en:'Sticker'},
    mt_poll:        {ru:'Опрос',                      en:'Poll'},
    mt_contact:     {ru:'Контакт',                    en:'Contact'},
    mt_location:    {ru:'Геопозиция',                 en:'Location'},
    // misc UI
    new_message:    {ru:'Новое сообщение',           en:'New message'},
    ctx_open_folder:{ru:'Открыть папку',             en:'Open folder'},
    dl_not_found_long:{ru:'Файл не найден — возможно, перемещён или удалён', en:'File not found — it may have been moved or deleted'},
    // common
    back:           {ru:'Назад',                     en:'Back'},
    loading:        {ru:'Загрузка…',                 en:'Loading…'},
    load_error:     {ru:'Ошибка загрузки',           en:'Load error'},
    error:          {ru:'Ошибка',                    en:'Error'},
    ok:             {ru:'ОК',                        en:'OK'},
    cancel:         {ru:'ОТМЕНА',                    en:'CANCEL'},
    del_upper:      {ru:'УДАЛИТЬ',                   en:'DELETE'},
    save_upper:     {ru:'СОХРАНИТЬ',                 en:'SAVE'},
};
function T(k){ var e=L[k]; if(!e) return k; return e[curLang()]||e.en||k; }
